environment = "prod"
region      = "ap-southeast-2"
tf_state_bucket = "prod-idlms-terraform-remotestate-272847363143"
log_group_tag_name    = "prod-DockerAPI"
ssm_param_name              = "/prod-cloudwatch/docker-config"
docker_log_group_name       = "/prod/docker/api"
ssm_tag_name                = "prod-docker-cloudwatch-config"
tf_state_region  = "ap-southeast-2"
